@startuml modified
autonumber

a -> b: Hello
b --> a: Hi
a -> b: This request is added
a -> b: This request is added one more time
a -> b: THIS IS CHANGE
a -> b: This message will be extended\nOH YEAH EXTENDED
a -> b: shortened

@enduml