@startuml include_part_a
skinparam MaxMessageSize 150
== <color #blue>Included part starts </color>==
A-[#blue]>B: <color #blue>We're from file **A!**</color>
A<-[#blue]-B: <color #blue>Max Message Size = 150</color>
== <color #blue>Included part ends </color>==
@enduml
